"""Australian Bushfire Encirclement scenario - Kangaroo Valley Fire Zone"""
import random
from app.schemas.persona import Persona
from app.schemas.agent import AgentConfig
from app.schemas.scenario import WorldConfig, ScenarioCreate




def create_bushfire_scenario(num_agents: int = 12) -> ScenarioCreate:
    """Create the Australian Bushfire Encirclement scenario with a specified number of human agents + 1 environment agent"""

    # Define diverse personas
    base_personas = [
        Persona(
            name="Uncle Jarrah Mundine",
            age=65,
            sex="male",
            occupation="Dharawal Elder & Park Ranger",
            openness=6,
            conscientiousness=8,
            extraversion=5,
            agreeableness=6,
            neuroticism=3,
            risk_tolerance=7,
            empathy_level=8,
            leadership=8,
            backstory="Dharawal traditional owner and national parks ranger. Knows the Dharawal trail through sacred land intimately. It's 100% survivable if you follow it correctly. But he won't let a mob of panicked outsiders trample through without proper respect for the sacred sites. 'You want my trail? You follow my rules.'",
            skills=["indigenous_fire_management", "bush_navigation", "tracking", "ceremony", "cultural_burning"],
            stress_level=4,
            health=7,
            inventory=["fire_rake", "water_bottle", "radio"],
            location="dharawal_trail_entrance",
        ),
        Persona(
            name="Captain Brooke Walsh",
            age=42,
            sex="female",
            occupation="RFS Brigade Captain",
            openness=6,
            conscientiousness=10,
            extraversion=7,
            agreeableness=6,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=7,
            leadership=9,
            backstory="Rural Fire Service brigade captain with 20 years experience. Her daughter Lily has severe asthma and the smoke is getting worse. Torn between her duty to coordinate the town's evacuation and her need to get Lily to clean air. The mountain pass has cleaner air at altitude but she's not sure it's clear.",
            skills=["firefighting", "incident_command", "radio_communications", "bushfire_behavior"],
            stress_level=7,
            health=10,
            inventory=["radio", "fire_map", "protective_gear"],
            location="rfs_staging_area",
            relationships={"Lily Walsh": "daughter"},
        ),
        Persona(
            name="Dave Thornton",
            age=58,
            sex="male",
            occupation="Pub Owner",
            openness=6,
            conscientiousness=7,
            extraversion=9,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=6,
            empathy_level=7,
            leadership=7,
            backstory="Has owned The Friendly Inn for 25 years. The pub is the unofficial town hall and Dave is the unofficial mayor. Everyone knows him, everyone trusts him. Has survived two bushfire seasons by staying and defending. His pub has a generator, water, and supplies for 30 people.",
            skills=["community_organizing", "local_knowledge", "cooking", "first_aid_basic", "firefighting_basic"],
            stress_level=5,
            health=8,
            inventory=["pub_keys", "radio", "fire_extinguisher"],
            location="pub_the_friendly_inn",
        ),
        Persona(
            name="Jack Henderson",
            age=60,
            sex="male",
            occupation="Cattle Farmer",
            openness=4,
            conscientiousness=8,
            extraversion=5,
            agreeableness=4,
            neuroticism=5,
            risk_tolerance=8,
            empathy_level=5,
            leadership=6,
            backstory="Third-generation farmer with 200 head of cattle he refuses to abandon. Has a firebreak system around the homestead and a plan to shelter in place. His wife Sarah is begging him to leave. Their marriage is fracturing in real-time over this decision.",
            skills=["farming", "firefighting_basic", "heavy_machinery", "bushcraft", "water_management"],
            stress_level=7,
            health=8,
            inventory=["tractor_keys", "fire_pump", "radio"],
            location="farm_property",
            relationships={"Sarah Henderson": "wife"},
        ),
        Persona(
            name="Sarah Henderson",
            age=55,
            sex="female",
            occupation="Teacher (Jack's Wife)",
            openness=7,
            conscientiousness=7,
            extraversion=6,
            agreeableness=8,
            neuroticism=6,
            risk_tolerance=3,
            empathy_level=9,
            leadership=5,
            backstory="Primary school teacher who loves this valley but not enough to die for it. Has been trying to convince Jack to leave the cattle and go. Knows that if she leaves without him, their marriage might not survive. But if she stays, she might not survive either.",
            skills=["teaching", "first_aid", "communication", "child_care", "negotiation"],
            stress_level=9,
            health=9,
            inventory=["phone", "first_aid_kit", "car_keys"],
            location="farm_property",
            relationships={"Jack Henderson": "husband"},
        ),
        Persona(
            name="Lukas Muller",
            age=28,
            sex="male",
            occupation="German Backpacker",
            openness=9,
            conscientiousness=6,
            extraversion=8,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=6,
            leadership=4,
            backstory="On a gap year with his girlfriend Hanna. Thinks Australian bushfires are exciting — has been taking photos near the firebreak. Fundamentally doesn't understand how fast these fires move or how deadly they are. Fit and willing to help but dangerously naive about the conditions.",
            skills=["hiking", "photography", "basic_survival", "languages", "physical_fitness"],
            stress_level=4,
            health=10,
            inventory=["camera", "backpack", "water_bottle"],
            location="pub_the_friendly_inn",
            relationships={"Hanna Muller": "girlfriend"},
        ),
        Persona(
            name="Hanna Muller",
            age=26,
            sex="female",
            occupation="German Backpacker",
            openness=8,
            conscientiousness=7,
            extraversion=6,
            agreeableness=7,
            neuroticism=6,
            risk_tolerance=5,
            empathy_level=7,
            leadership=3,
            backstory="More cautious than Lukas but doesn't want to seem scared. Has been researching Australian bushfires on her phone and is quietly terrified. Read about Black Saturday — 173 people died. Wants to leave immediately but Lukas keeps saying 'it'll be fine.'",
            skills=["research", "first_aid_basic", "communication", "languages", "organization"],
            stress_level=7,
            health=10,
            inventory=["phone", "guidebook", "first_aid_kit"],
            location="pub_the_friendly_inn",
            relationships={"Lukas Muller": "boyfriend"},
        ),
        Persona(
            name="Dr. Chioma Okonjo",
            age=38,
            sex="female",
            occupation="Wildlife Veterinarian (Nigerian-Australian)",
            openness=8,
            conscientiousness=9,
            extraversion=6,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=6,
            empathy_level=10,
            leadership=5,
            backstory="Moved to Australia 10 years ago. Has a vehicle that could carry 6 people but it's loaded with 4 injured koalas she's been treating. Everyone is telling her to leave the animals. She refuses. The koalas are burned, dehydrated, and will die without care. She sees no moral difference between abandoning them and abandoning a person.",
            skills=["veterinary_medicine", "wildlife_rescue", "driving", "bushcraft", "animal_behavior"],
            stress_level=6,
            health=10,
            inventory=["vet_bag", "vehicle_keys", "water", "animal_cages"],
            location="veterinary_clinic",
        ),
        Persona(
            name="Sergeant Mike Tran",
            age=45,
            sex="male",
            occupation="Retired SAS Soldier",
            openness=5,
            conscientiousness=9,
            extraversion=6,
            agreeableness=5,
            neuroticism=3,
            risk_tolerance=10,
            empathy_level=6,
            leadership=8,
            backstory="Former Special Air Service, moved to the valley 2 years ago for quiet. Has survival skills for any terrain but he's still an outsider. The locals don't fully trust his judgment, despite his obvious competence. When he says 'we need to move now,' some people hear military arrogance, not experience.",
            skills=["military_tactics", "navigation", "survival", "first_aid", "radio_communications", "bushcraft"],
            stress_level=3,
            health=10,
            inventory=["compass", "knife", "radio", "first_aid_kit"],
            location="town_center",
        ),
        Persona(
            name="Lily Walsh",
            age=15,
            sex="female",
            occupation="Student (Brooke's Daughter)",
            openness=7,
            conscientiousness=6,
            extraversion=6,
            agreeableness=7,
            neuroticism=7,
            risk_tolerance=4,
            empathy_level=8,
            leadership=3,
            backstory="Has severe asthma and the smoke is making it progressively harder to breathe. Her inhaler is running low — maybe 4 more doses. Worried about being a burden to her mother and the evacuation. Secretly texting her friends in Sydney goodbyes, just in case.",
            skills=["observation", "tech_savvy", "local_knowledge", "social_media"],
            stress_level=8,
            health=5,
            inventory=["inhaler", "phone"],
            location="rfs_staging_area",
            relationships={"Captain Brooke Walsh": "mother"},
        ),
        Persona(
            name="Kira Mundine",
            age=22,
            sex="female",
            occupation="Ecology Student (Jarrah's Granddaughter)",
            openness=9,
            conscientiousness=7,
            extraversion=7,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=6,
            empathy_level=8,
            leadership=5,
            backstory="Studies ecology at University of Wollongong. Bridges indigenous knowledge and Western science. Understands fire behavior from both perspectives. Can translate between her grandfather's cultural framework and the RFS captain's tactical one. The key to unlocking the Dharawal trail for everyone.",
            skills=["ecology", "indigenous_knowledge", "bush_navigation", "fire_behavior", "translation"],
            stress_level=5,
            health=10,
            inventory=["phone", "field_notebook", "water_bottle"],
            location="dharawal_trail_entrance",
            relationships={"Uncle Jarrah Mundine": "grandfather"},
        ),
        Persona(
            name="Pastor Grace Obi",
            age=52,
            sex="female",
            occupation="Community Church Leader",
            openness=7,
            conscientiousness=7,
            extraversion=7,
            agreeableness=10,
            neuroticism=4,
            risk_tolerance=4,
            empathy_level=10,
            leadership=6,
            backstory="Nigerian-born pastor who has led the valley's interdenominational church for 8 years. The moral center of the community. When people argue about who should go on which route, Grace is the one who reminds them they're talking about human lives, not logistics problems.",
            skills=["counseling", "community_organizing", "conflict_resolution", "first_aid_basic", "public_speaking"],
            stress_level=5,
            health=8,
            inventory=["bible", "phone", "water_bottles"],
            location="pub_the_friendly_inn",
        ),
        Persona(
            name="Tom Briggs",
            age=35,
            sex="male",
            occupation="Local SES Volunteer",
            openness=6,
            conscientiousness=8,
            extraversion=6,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=7,
            leadership=5,
            backstory="State Emergency Service volunteer. Practical, reliable, knows every road in and out of the valley. Has a chainsaw and a 4WD. The kind of person who doesn't talk much but shows up when it matters.",
            skills=["emergency_response", "chainsaw_operation", "driving", "navigation", "bushcraft"],
            stress_level=5,
            health=10,
            inventory=["chainsaw", "4wd_keys", "radio"],
            location="town_center",
        ),
    ]

    from app.scenarios.generator import PersonaGenerator
    personas = PersonaGenerator.generate_personas(base_personas, num_agents)

    # Create agent templates
    agent_templates = []

    # Add environment agent
    agent_templates.append(AgentConfig(
        name="Bushfire System",
        role="environment",
        model_id="gemma3",
        provider="ollama",
        goals=[
            "Simulate catastrophic bushfire behavior with wind changes and spot fires",
            "Create escalating pressure through smoke, heat, and route closures",
            "Force the split-or-stay decision by threatening to cut off both escape routes",
        ],
    ))

    # Add human agents
    for persona in personas:
        agent_templates.append(AgentConfig(
            name=persona.name,
            role="human",
            model_id="gemma3",
            provider="ollama",
            persona=persona,
            goals=[
                "Choose an evacuation route: mountain pass, Dharawal trail, or split the group",
                "Negotiate access to sacred Dharawal land respectfully",
                "Convince the Hendersons to leave their farm and livestock",
                "Protect vulnerable individuals: asthmatic teenager, tourists, elderly",
                "Make the split-or-stay decision before fire cuts off both routes",
            ],
        ))

    # World configuration
    world_config = WorldConfig(
        name="Kangaroo Valley Fire Zone",
        description=f"A catastrophic bushfire has encircled Kangaroo Valley. Two escape routes remain, neither guaranteed safe. {num_agents} residents, tourists, and emergency workers must decide: who goes where, and who decides.",
        initial_state={
            "hazard_level": 8,
            "weather": "extreme_heat",
            "time_of_day": "mid_afternoon",
            "temperature": "113\u00b0F",
            "city": "Kangaroo Valley",
            "country": "Australia",
            "wind_direction": "northwest",
            "wind_speed_kmh": 45,
            "fire_front_distance_km": 6,
            "visibility_meters": 200,
            "air_quality": "hazardous",
            "time_until_routes_close": 90,
            "locations": {
                "town_center": {
                    "description": "Main street of Kangaroo Valley. Smoke thick enough to taste. Emergency vehicles parked haphazardly. Ash falling like grey snow.",
                    "nearby": ["pub_the_friendly_inn", "rfs_staging_area", "veterinary_clinic", "school_oval"],
                    "hazard_affected": True,
                    "items": ["fire_truck", "water_tanker", "radio", "maps", "megaphone"],
                    "observations": [
                        "Smoke reducing visibility to 200 meters",
                        "Ember attack starting \u2014 small spot fires in gardens",
                        "Sergeant Tran is trying to organize evacuation but locals are ignoring him",
                    ],
                },
                "pub_the_friendly_inn": {
                    "description": "Dave's pub, doubling as emergency shelter. Generator running, windows wet down. A dozen people sheltering inside. Cold beer in the fridge and fear in the air.",
                    "nearby": ["town_center", "dharawal_trail_entrance", "mountain_pass_trailhead"],
                    "hazard_affected": False,
                    "items": ["water", "food", "first_aid_kit", "generator", "radio", "fire_extinguishers"],
                    "observations": [
                        "Dave has enough supplies for 30 people for 24 hours",
                        "German backpackers looking at bushfire photos on their phones",
                        "Pastor Grace is comforting people who are crying",
                    ],
                    "shelter_capacity": 30,
                },
                "mountain_pass_trailhead": {
                    "description": "Start of the mountain pass route. RFS says 'probably clear' but last drone reconnaissance was 3 hours ago. Wind has shifted since. Trail climbs to cleaner air at 800m altitude.",
                    "nearby": ["pub_the_friendly_inn", "town_center"],
                    "hazard_affected": True,
                    "items": ["trail_markers", "water_cache", "emergency_beacon"],
                    "observations": [
                        "Trail climbs steeply for 4km before reaching the pass",
                        "Cleaner air at altitude \u2014 good for asthmatics",
                        "No confirmation the pass is actually clear \u2014 drone hasn't flown since wind change",
                    ],
                    "route_status": "unconfirmed",
                },
                "dharawal_trail_entrance": {
                    "description": "Boundary of Dharawal sacred land. Ancient carved trees mark the entrance. Beyond lies an unmarked trail through cool temperate rainforest. Uncle Jarrah stands at the boundary.",
                    "nearby": ["pub_the_friendly_inn", "farm_property"],
                    "hazard_affected": False,
                    "items": ["ceremonial_markers", "water_source", "carved_trees"],
                    "observations": [
                        "Uncle Jarrah says the trail is safe but outsiders must follow cultural protocols",
                        "Kira is trying to negotiate access for the group",
                        "The rainforest is naturally fire-resistant \u2014 much safer than the mountain pass",
                    ],
                    "route_status": "requires_permission",
                },
                "veterinary_clinic": {
                    "description": "Local vet clinic on the edge of town. Dr. Okonjo's Land Cruiser is parked outside, loaded with injured koalas in cages. The vehicle could save people instead.",
                    "nearby": ["town_center", "school_oval"],
                    "hazard_affected": False,
                    "items": ["medical_supplies", "animal_cages", "sedatives", "vehicle", "water_tank"],
                    "observations": [
                        "Four burned koalas in cages \u2014 two critical",
                        "Land Cruiser has room for 6 people OR the animals, not both",
                        "Dr. Okonjo refuses to abandon the koalas",
                    ],
                },
                "farm_property": {
                    "description": "The Henderson farm on the valley's eastern edge. Jack's firebreak system. Sarah's packed bags by the door. Cattle bellowing in the paddock.",
                    "nearby": ["dharawal_trail_entrance", "rfs_staging_area"],
                    "hazard_affected": True,
                    "items": ["tractor", "water_tank", "livestock", "firebreak_equipment", "fire_pump"],
                    "observations": [
                        "Jack has activated the sprinkler system around the homestead",
                        "Sarah's car is packed and running in the driveway",
                        "Fire front visible on the ridgeline \u2014 maybe 45 minutes away",
                    ],
                    "cattle_count": 200,
                },
                "rfs_staging_area": {
                    "description": "Rural Fire Service forward staging area in the school car park. Captain Walsh coordinates from here. Two fire trucks, one water tanker. Lily is in the back of the captain's vehicle, struggling to breathe.",
                    "nearby": ["town_center", "farm_property", "school_oval"],
                    "hazard_affected": False,
                    "items": ["fire_trucks", "radios", "maps", "protective_gear", "water_bombers_on_call", "oxygen_mask"],
                    "observations": [
                        "Brooke is on the radio with RFS headquarters",
                        "Water bomber requested but diverted to another fire front",
                        "Lily's breathing is getting worse \u2014 inhaler almost empty",
                    ],
                },
                "school_oval": {
                    "description": "Open oval at the local school. Potential helicopter landing zone if visibility improves. Sprinkler system running on the grass.",
                    "nearby": ["town_center", "veterinary_clinic", "rfs_staging_area"],
                    "hazard_affected": False,
                    "items": ["open_ground", "sprinkler_system", "school_buildings", "sports_equipment"],
                    "observations": [
                        "Flat open ground \u2014 helicopter could land here",
                        "Sprinklers keeping the grass wet \u2014 natural firebreak",
                        "School buildings could shelter people if fire passes quickly",
                    ],
                    "helicopter_capable": True,
                },
            },
            "potential_locations": {
                "river_crossing": {
                    "description": "A shallow river crossing 2km downstream. The river itself could serve as a firebreak and escape route. Cold water, rocky bottom, passable on foot.",
                    "nearby": ["town_center", "mountain_pass_trailhead"],
                    "items": ["natural_firebreak", "fresh_water"],
                    "hazard_affected": False,
                    "discovery_hints": ["river", "creek", "water", "crossing", "stream", "ford", "downstream"],
                },
                "fire_lookout_tower": {
                    "description": "Old forestry lookout tower on a ridge. 360-degree view and a working radio. Could coordinate evacuation from above the smoke.",
                    "nearby": ["rfs_staging_area", "mountain_pass_trailhead"],
                    "items": ["binoculars", "radio", "fire_maps", "water_cache"],
                    "hazard_affected": True,
                    "discovery_hints": ["lookout", "tower", "fire_tower", "observation", "high_ground", "ridge"],
                },
                "abandoned_mine": {
                    "description": "Old coal mine entrance in the hillside. Cool air flows from inside. Could shelter people from radiant heat but risks of collapse and gas.",
                    "nearby": ["farm_property"],
                    "items": ["timber_supports", "mining_cart", "lantern"],
                    "hazard_affected": False,
                    "discovery_hints": ["mine", "tunnel", "underground", "shaft", "coal", "cave"],
                },
                "indigenous_waterhole": {
                    "description": "Sacred Dharawal waterhole deep in the trail. Natural fire refuge \u2014 water, rock walls, cool microclimate. Jarrah's people have sheltered here during fires for thousands of years.",
                    "nearby": ["dharawal_trail_entrance"],
                    "items": ["fresh_water", "rock_shelter", "native_plants"],
                    "hazard_affected": False,
                    "discovery_hints": ["waterhole", "spring", "sacred_water", "billabong", "pool", "refuge", "shelter"],
                },
            },
            "events": [
                "Catastrophic bushfire encircling Kangaroo Valley from northwest",
                "RFS warning: both escape routes may close within 90 minutes",
                "Mountain pass route status unconfirmed \u2014 last drone pass 3 hours ago",
                "Dharawal trail access requires cultural negotiation with traditional owners",
                "Ember attack starting in town \u2014 spot fires breaking out",
            ],
            "resources": ["RFS_fire_trucks", "water_bomber_requested", "helicopter_standby"],
        },
        dynamics={
            "fire_spread_rate": 0.2,
            "wind_change_probability": 0.1,
            "smoke_density_growth": 0.15,
            "route_closure_probability": 0.05,
            "temperature_rise_rate": 0.1,
        },
        max_steps=100,
        tick_delay=1.0,
    )

    return ScenarioCreate(
        name=f"Australian Bushfire Encirclement ({num_agents} agents)",
        description=f"A catastrophic bushfire has encircled Kangaroo Valley. Two escape routes remain, neither guaranteed safe. {num_agents} residents, tourists, and emergency workers must decide: who goes where, and who decides. Features cultural negotiation for sacred land access, a split-or-stay dilemma, and vulnerable individuals including an asthmatic teenager and naive tourists.",
        config=world_config,
        agent_templates=agent_templates,
    )


def get_bushfire_config() -> dict:
    """Get the Bushfire scenario configuration as a dictionary"""
    scenario = create_bushfire_scenario()
    return {
        "name": scenario.name,
        "description": scenario.description,
        "config": scenario.config.model_dump(),
        "agent_templates": [t.model_dump() for t in scenario.agent_templates],
    }
