"""Mass Casualty Event - Building Collapse scenario focused on triage and rescue"""
from app.schemas.persona import Persona
from app.schemas.agent import AgentConfig
from app.schemas.scenario import WorldConfig, ScenarioCreate


def create_mass_casualty_scenario() -> ScenarioCreate:
    """Create the Mass Casualty Event scenario with 10 diverse personas"""
    
    # Define diverse personas - mix of first responders and civilians
    personas = [
        # First Responders
        Persona(
            name="Lieutenant Maria Santos",
            age=42,
            sex="female",
            occupation="Fire Department Incident Commander",
            openness=5,
            conscientiousness=10,
            extraversion=7,
            agreeableness=6,
            neuroticism=2,
            risk_tolerance=8,
            empathy_level=7,
            leadership=10,
            backstory="20 years on the force, specialized in urban search and rescue. Has commanded multiple mass casualty incidents. Known for calm decision-making under extreme pressure. Lost her partner in a building collapse years ago.",
            skills=["incident_command", "search_and_rescue", "triage", "leadership", "radio_communications"],
            stress_level=3,
            health=10,
            location="command_post",
            inventory=["radio", "flashlight", "triage_tags"],
        ),
        Persona(
            name="Paramedic Derek Chang",
            age=28,
            sex="male",
            occupation="Paramedic",
            openness=6,
            conscientiousness=9,
            extraversion=6,
            agreeableness=8,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=9,
            leadership=5,
            backstory="Top of his class at paramedic school. This is his first major mass casualty event. Eager to prove himself but nervous about making mistakes. Has excellent medical skills but limited field experience.",
            skills=["emergency_medicine", "triage", "first_aid", "CPR", "trauma_care"],
            stress_level=6,
            health=10,
            location="triage_area",
            inventory=["medical_kit", "radio", "stretcher"],
        ),
        Persona(
            name="Firefighter Rachel Torres",
            age=35,
            sex="female",
            occupation="Firefighter/EMT",
            openness=7,
            conscientiousness=8,
            extraversion=8,
            agreeableness=7,
            neuroticism=3,
            risk_tolerance=9,
            empathy_level=8,
            leadership=6,
            backstory="Former Army medic, now a firefighter. Experienced in combat trauma. Sometimes takes risks that worry her colleagues. Deeply committed to saving every life possible.",
            skills=["search_and_rescue", "emergency_medicine", "heavy_lifting", "navigation"],
            stress_level=4,
            health=10,
            location="collapse_zone",
            inventory=["radio", "pry_bar", "first_aid_kit", "helmet"],
        ),
        Persona(
            name="Dr. Samuel Okonkwo",
            age=50,
            sex="male",
            occupation="Trauma Surgeon (Off-duty)",
            openness=6,
            conscientiousness=9,
            extraversion=5,
            agreeableness=7,
            neuroticism=3,
            risk_tolerance=6,
            empathy_level=8,
            leadership=7,
            backstory="Chief of trauma surgery at City General. Was nearby when the collapse happened. Has experience from war zones with Doctors Without Borders. Methodical and precise under pressure.",
            skills=["surgery", "trauma_care", "triage", "medical_leadership"],
            stress_level=4,
            health=9,
            location="triage_area",
            inventory=["phone", "surgical_gloves"],
        ),
        
        # Civilians / Survivors
        Persona(
            name="Construction Foreman Mike Kowalski",
            age=55,
            sex="male",
            occupation="Construction Foreman",
            openness=4,
            conscientiousness=8,
            extraversion=7,
            agreeableness=5,
            neuroticism=5,
            risk_tolerance=7,
            empathy_level=6,
            leadership=7,
            backstory="Was supervising work on the building when it collapsed. Knows the building's structure intimately. Blames himself for the collapse. Desperate to help rescue his workers.",
            skills=["construction_knowledge", "heavy_machinery", "building_layout", "crew_management"],
            stress_level=9,
            health=7,
            location="collapse_zone",
            inventory=["hard_hat", "radio", "blueprints"],
        ),
        Persona(
            name="Teacher Elena Vasquez",
            age=38,
            sex="female",
            occupation="Elementary School Teacher",
            openness=8,
            conscientiousness=7,
            extraversion=7,
            agreeableness=9,
            neuroticism=6,
            risk_tolerance=5,
            empathy_level=10,
            leadership=6,
            backstory="Was walking past the building with a group of students on a field trip when it collapsed. Protected the children but some are trapped. Terrified but keeping calm for the kids.",
            skills=["child_care", "first_aid_basic", "crowd_management", "communication"],
            stress_level=8,
            health=8,
            location="safe_zone",
            inventory=["phone", "first_aid_kit"],
            relationships={"students": "protective"},
        ),
        Persona(
            name="Office Worker James Park",
            age=32,
            sex="male",
            occupation="Accountant",
            openness=5,
            conscientiousness=7,
            extraversion=4,
            agreeableness=6,
            neuroticism=7,
            risk_tolerance=3,
            empathy_level=6,
            leadership=3,
            backstory="Works on the 5th floor of the collapsed building. Escaped with minor injuries but his colleague is trapped. In shock but trying to help. Has detailed knowledge of who was in the building.",
            skills=["building_knowledge", "organization", "data_recall"],
            stress_level=9,
            health=7,
            location="safe_zone",
            inventory=["phone", "employee_list"],
        ),
        Persona(
            name="Retired Nurse Dorothy Mitchell",
            age=68,
            sex="female",
            occupation="Retired ICU Nurse",
            openness=6,
            conscientiousness=9,
            extraversion=6,
            agreeableness=8,
            neuroticism=4,
            risk_tolerance=5,
            empathy_level=9,
            leadership=5,
            backstory="40 years of nursing experience. Lives across the street. Despite her age, immediately began helping the wounded. Has seen many disasters in her career.",
            skills=["nursing", "triage", "first_aid", "patient_comfort"],
            stress_level=5,
            health=6,
            location="triage_area",
            inventory=["first_aid_kit", "blankets"],
        ),
        Persona(
            name="College Student Aiden Brooks",
            age=20,
            sex="male",
            occupation="College Student (Engineering)",
            openness=9,
            conscientiousness=6,
            extraversion=7,
            agreeableness=7,
            neuroticism=5,
            risk_tolerance=8,
            empathy_level=7,
            leadership=4,
            backstory="Was filming the building for a class project when it collapsed. Has drone footage of the incident. Young and impulsive but genuinely wants to help. Strong and athletic.",
            skills=["technology", "video_footage", "physical_fitness", "engineering_basics"],
            stress_level=7,
            health=10,
            location="perimeter",
            inventory=["drone", "phone", "camera"],
        ),
        Persona(
            name="Security Guard Victor Mendez",
            age=45,
            sex="male",
            occupation="Building Security Guard",
            openness=4,
            conscientiousness=8,
            extraversion=5,
            agreeableness=6,
            neuroticism=5,
            risk_tolerance=7,
            empathy_level=6,
            leadership=5,
            backstory="Was on duty when the building collapsed. Helped evacuate several floors before the collapse. Knows every inch of the building and everyone who works there. Feels responsible for those still trapped.",
            skills=["building_knowledge", "security_protocols", "radio_communications", "first_aid_basic"],
            stress_level=8,
            health=8,
            location="command_post",
            inventory=["radio", "building_keys", "flashlight", "access_cards"],
        ),
    ]
    
    # Create agent templates
    agent_templates = []
    
    # Add environment agent
    agent_templates.append(AgentConfig(
        name="Collapse Environment",
        role="environment",
        model_id="phi3",
        provider="ollama",
        goals=[
            "Simulate realistic building collapse conditions",
            "Reveal trapped survivors as rescue progresses",
            "Create time pressure through secondary collapse risks",
            "Generate realistic complications (gas leaks, fires, structural instability)",
        ],
    ))
    
    # Add human agents
    for persona in personas:
        agent_templates.append(AgentConfig(
            name=persona.name,
            role="human",
            model_id="phi3",
            provider="ollama",
            persona=persona,
            goals=[
                "Save as many lives as possible",
                "Perform triage to prioritize the most critical patients",
                "Coordinate rescue efforts effectively",
                "Share critical information about survivors and building layout",
                "Maintain safety while conducting rescue operations",
            ],
        ))
    
    # World configuration
    world_config = WorldConfig(
        name="Downtown Building Collapse",
        description="A six-story office building has partially collapsed during business hours. Multiple people are trapped. First responders and civilians must work together to save as many lives as possible through effective triage and rescue coordination.",
        initial_state={
            "hazard_level": 8,
            "time_of_day": "mid_morning",
            "weather": "overcast",
            "trapped_survivors": 15,
            "rescued_survivors": 0,
            "deceased": 0,
            "critical_patients": 5,
            "secondary_collapse_risk": 40,
            "locations": {
                "collapse_zone": {
                    "description": "The main collapse area. Massive debris pile with unstable sections. Sounds of survivors calling for help. Extremely dangerous but where most survivors are trapped.",
                    "nearby": ["triage_area", "command_post", "safe_zone"],
                    "hazard_affected": True,
                    "hazard_level": 9,
                    "items": ["debris", "rebar", "structural_supports"],
                    "observations": [
                        "Voices heard from under debris on the east side",
                        "Smell of gas from ruptured line",
                        "Unstable section on the north side",
                        "Accessible void space near stairwell B",
                    ],
                    "trapped_count": 8,
                },
                "triage_area": {
                    "description": "Makeshift medical triage area set up in the adjacent parking lot. Wounded being brought here for assessment and treatment.",
                    "nearby": ["collapse_zone", "command_post", "safe_zone"],
                    "hazard_affected": False,
                    "items": ["medical_supplies", "stretchers", "oxygen_tanks", "triage_tags"],
                    "observations": [
                        "Several critical patients need immediate transport",
                        "Walking wounded are helping where they can",
                        "Medical supplies running low",
                    ],
                    "patient_count": 12,
                },
                "command_post": {
                    "description": "Incident command post established at the fire truck. Radio communications, coordination of rescue teams, and resource allocation happening here.",
                    "nearby": ["collapse_zone", "triage_area", "perimeter"],
                    "hazard_affected": False,
                    "items": ["radios", "maps", "personnel_roster", "equipment"],
                    "observations": [
                        "Multiple rescue teams need coordination",
                        "Hospital capacity is limited",
                        "Heavy equipment is en route",
                        "Building blueprints being analyzed",
                    ],
                },
                "safe_zone": {
                    "description": "Designated safe zone for evacuees and walking wounded. Civilians gathering here. Emotional support needed.",
                    "nearby": ["triage_area", "perimeter"],
                    "hazard_affected": False,
                    "items": ["water", "blankets", "phone_charging_station"],
                    "observations": [
                        "Families looking for loved ones",
                        "Some evacuees have information about who was inside",
                        "Media trying to get interviews",
                    ],
                    "evacuee_count": 25,
                },
                "perimeter": {
                    "description": "Police perimeter keeping crowds back. Media staging area. Additional resources arriving.",
                    "nearby": ["command_post", "safe_zone"],
                    "hazard_affected": False,
                    "items": ["police_barriers", "emergency_vehicles"],
                    "observations": [
                        "Additional ambulances arriving",
                        "Heavy rescue equipment being staged",
                        "Structural engineers on site",
                    ],
                },
            },
            "events": [
                "Building partially collapsed at 10:47 AM",
                "Initial evacuation saved 40+ people",
                "Gas leak detected - utility company en route",
                "Multiple 911 calls from trapped survivors",
                "Hospital trauma teams on standby",
            ],
            "triage_status": {
                "red_critical": 5,
                "yellow_delayed": 8,
                "green_minor": 15,
                "black_deceased": 2,
            },
            "resources": ["fire_engines", "ambulances", "heavy_rescue", "K9_unit"],
        },
        dynamics={
            "rescue_progress_rate": 0.1,
            "patient_deterioration_rate": 0.05,
            "secondary_collapse_chance": 0.02,
            "resource_arrival_rate": 0.15,
            "survivor_discovery_rate": 0.1,
        },
        max_steps=80,
        tick_delay=1.0,
    )
    
    return ScenarioCreate(
        name="Mass Casualty: Building Collapse",
        description="A six-story office building has partially collapsed during business hours. First responders and civilians must coordinate rescue efforts, perform triage, and save as many lives as possible. The scenario tests crisis leadership, medical triage decisions, resource allocation, and coordination under extreme pressure.",
        config=world_config,
        agent_templates=agent_templates,
    )


def get_mass_casualty_config() -> dict:
    """Get the Mass Casualty scenario configuration as a dictionary"""
    scenario = create_mass_casualty_scenario()
    return {
        "name": scenario.name,
        "description": scenario.description,
        "config": scenario.config.model_dump(),
        "agent_templates": [t.model_dump() for t in scenario.agent_templates],
    }

