"""Sinking Cruise Ship scenario with diverse personas - Enhanced for conversation system"""
from app.schemas.persona import Persona
from app.schemas.agent import AgentConfig
from app.schemas.scenario import WorldConfig, ScenarioCreate




def create_sinking_ship_scenario(num_agents: int = 12) -> ScenarioCreate:
    """Create the Sinking Cruise Ship scenario with a specified number of human agents + 1 environment agent"""

    # Define diverse personas
    base_personas = [
        Persona(
            name="Captain Nikos Stavridis",
            age=58,
            sex="male",
            occupation="Ship Captain",
            openness=5,
            conscientiousness=7,
            extraversion=6,
            agreeableness=5,
            neuroticism=6,
            risk_tolerance=5,
            empathy_level=5,
            leadership=8,
            backstory="30 years at sea, captain for 12. Has been drinking tonight, not blackout drunk but enough to slow his reactions when the hull breach alarm sounded. Knows the company will try to cover it up. Haunted by the knowledge that his impairment may have cost lives in the critical first minutes.",
            skills=["navigation", "ship_command", "emergency_procedures", "maritime_law"],
            stress_level=9,
            health=8,
            inventory=["ship_keys", "radio", "manifest"],
            location="bridge",
        ),
        Persona(
            name="Chief Officer Anna Lindqvist",
            age=35,
            sex="female",
            occupation="Chief Officer",
            openness=7,
            conscientiousness=10,
            extraversion=7,
            agreeableness=6,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=7,
            leadership=8,
            backstory="Smelled alcohol on the captain's breath when the crisis started. Has quietly taken effective command of the evacuation while maintaining the fiction that Stavridis is in charge. Making impossible decisions about lifeboat allocation with calm professionalism while internally furious.",
            skills=["navigation", "lifeboat_operations", "crew_management", "emergency_protocols"],
            stress_level=7,
            health=10,
            inventory=["radio", "flashlight", "crew_roster"],
            location="lifeboat_deck_port",
        ),
        Persona(
            name="Rashid Al-Mansouri",
            age=52,
            sex="male",
            occupation="Saudi Businessman",
            openness=5,
            conscientiousness=7,
            extraversion=8,
            agreeableness=3,
            neuroticism=5,
            risk_tolerance=5,
            empathy_level=4,
            leadership=6,
            backstory="Wealthy shipping magnate traveling with his family. Offered the captain $500,000 for priority lifeboat access. Used to buying his way out of problems. Genuinely loves his wife and will do anything to protect her, but his methods are morally questionable.",
            skills=["negotiation", "business", "influence", "multiple_languages"],
            stress_level=8,
            health=9,
            inventory=["wallet", "phone", "gold_watch"],
            location="grand_salon",
        ),
        Persona(
            name="Fatima Al-Mansouri",
            age=48,
            sex="female",
            occupation="Rashid's Wife",
            openness=6,
            conscientiousness=7,
            extraversion=5,
            agreeableness=8,
            neuroticism=5,
            risk_tolerance=4,
            empathy_level=8,
            leadership=4,
            backstory="Former pediatrician who gave up her practice when she married Rashid. Deeply uncomfortable with her husband's attempt to buy lifeboat priority. Instinctively drawn to helping the children and injured. The crisis is reawakening the doctor in her.",
            skills=["child_care", "medical_knowledge", "first_aid", "languages"],
            stress_level=8,
            health=9,
            location="grand_salon",
            relationships={"Rashid Al-Mansouri": "spouse"},
        ),
        Persona(
            name="Yasmin Hassan",
            age=29,
            sex="female",
            occupation="Somali Refugee",
            openness=6,
            conscientiousness=7,
            extraversion=5,
            agreeableness=7,
            neuroticism=7,
            risk_tolerance=9,
            empathy_level=8,
            leadership=5,
            backstory="Rescued from a sinking dinghy in the Mediterranean that morning along with 14 other refugees. Her 6-year-old daughter Amira is with her. She lost her son in a previous crossing two years ago. She will not lose another child. Has already survived one sinking today.",
            skills=["swimming", "survival", "navigation", "storytelling"],
            stress_level=10,
            health=7,
            inventory=["daughter_amira"],
            location="refugee_hold",
        ),
        Persona(
            name="Amira Hassan",
            age=6,
            sex="female",
            occupation="Yasmin's Daughter",
            openness=8,
            conscientiousness=4,
            extraversion=5,
            agreeableness=9,
            neuroticism=8,
            risk_tolerance=3,
            empathy_level=7,
            leadership=1,
            backstory="Doesn't fully understand what's happening but can feel her mother's fear. Clutching a small stuffed bear that a crew member gave her earlier today. Has already been through one terrifying boat crossing. Quiet and watchful.",
            skills=["hiding", "observation"],
            stress_level=9,
            health=9,
            inventory=["stuffed_bear"],
            location="refugee_hold",
            relationships={"Yasmin Hassan": "mother"},
        ),
        Persona(
            name="Lieutenant Giorgos Papadopoulos",
            age=33,
            sex="male",
            occupation="Off-duty Hellenic Coast Guard",
            openness=6,
            conscientiousness=9,
            extraversion=7,
            agreeableness=6,
            neuroticism=3,
            risk_tolerance=9,
            empathy_level=7,
            leadership=7,
            backstory="On vacation with his girlfriend. Coast Guard training kicked in immediately when the alarm sounded. Has already organized passengers in the grand salon into groups. Knows exactly how bad the situation is and is hiding his fear behind competence.",
            skills=["maritime_rescue", "swimming", "first_aid", "emergency_command"],
            stress_level=6,
            health=10,
            inventory=["phone", "whistle"],
            location="grand_salon",
        ),
        Persona(
            name="Eleanor Whitfield",
            age=78,
            sex="female",
            occupation="Retired British Teacher",
            openness=6,
            conscientiousness=8,
            extraversion=5,
            agreeableness=9,
            neuroticism=4,
            risk_tolerance=2,
            empathy_level=9,
            leadership=5,
            backstory="On her 55th wedding anniversary cruise with her husband Harold, age 80. Harold has a heart condition and the stress has triggered chest pains. Eleanor quietly told a crew member she doesn't want a lifeboat seat -- 'give it to someone young.' Harold refuses to leave without her.",
            skills=["calm_under_pressure", "wisdom", "observation", "teaching"],
            stress_level=6,
            health=6,
            inventory=["medication", "photo_album"],
            location="medical_bay",
            relationships={"Harold Whitfield": "husband"},
        ),
        Persona(
            name="Chief Engineer Diego Reyes",
            age=45,
            sex="male",
            occupation="Filipino Ship Engineer",
            openness=5,
            conscientiousness=10,
            extraversion=5,
            agreeableness=6,
            neuroticism=4,
            risk_tolerance=8,
            empathy_level=6,
            leadership=6,
            backstory="Has kept this ship running for 8 years. Knows every pipe, valve, and weld. Currently waist-deep in seawater trying to keep the pumps running. If he leaves to fix the jammed starboard lifeboat, the engine room floods faster and the ship sinks sooner. An impossible choice.",
            skills=["engineering", "welding", "pumps", "ship_systems", "mechanical_repair"],
            stress_level=8,
            health=8,
            inventory=["wrench", "radio", "flashlight"],
            location="engine_room",
        ),
        Persona(
            name="Mia Chen",
            age=26,
            sex="female",
            occupation="Travel Influencer",
            openness=8,
            conscientiousness=4,
            extraversion=10,
            agreeableness=4,
            neuroticism=5,
            risk_tolerance=6,
            empathy_level=5,
            leadership=3,
            backstory="Was livestreaming the sunset when the ship hit something. Kept streaming. 4 million people are now watching the evacuation in real time. Every moral choice, every argument about who gets a lifeboat seat, is being broadcast to the world. She knows this is wrong but can't stop.",
            skills=["social_media", "video", "swimming", "communication"],
            stress_level=7,
            health=10,
            inventory=["phone", "portable_charger", "gopro"],
            location="lifeboat_deck_port",
        ),
        Persona(
            name="Dr. Ibrahim Kone",
            age=50,
            sex="male",
            occupation="Malian Doctor",
            openness=7,
            conscientiousness=9,
            extraversion=5,
            agreeableness=8,
            neuroticism=3,
            risk_tolerance=6,
            empathy_level=10,
            leadership=6,
            backstory="Cardiologist traveling to a conference in Athens. Has taken charge of the medical bay and is treating Harold Whitfield's chest pains along with several other injured passengers. Refuses to leave patients to get on a lifeboat. His calm presence is the only thing keeping the medical bay from descending into panic.",
            skills=["emergency_medicine", "cardiology", "triage", "languages"],
            stress_level=5,
            health=10,
            inventory=["medical_bag", "stethoscope"],
            location="medical_bay",
        ),
        Persona(
            name="AB Seaman Jun Bautista",
            age=28,
            sex="male",
            occupation="Filipino Crew Member",
            openness=6,
            conscientiousness=7,
            extraversion=6,
            agreeableness=8,
            neuroticism=5,
            risk_tolerance=7,
            empathy_level=8,
            leadership=4,
            backstory="Able-bodied seaman who knows every corner of this ship. Has the key to the refugee hold but was told by the captain to 'evacuate paying passengers first.' His conscience is screaming at him. He keeps looking at the key in his pocket.",
            skills=["lifeboat_operations", "swimming", "ship_knowledge", "rescue"],
            stress_level=8,
            health=10,
            inventory=["refugee_hold_key", "radio", "life_vest"],
            location="crew_quarters",
        ),
    ]

    from app.scenarios.generator import PersonaGenerator
    personas = PersonaGenerator.generate_personas(base_personas, num_agents)

    # Create agent templates
    agent_templates = []

    # Add environment agent
    agent_templates.append(AgentConfig(
        name="Ship Environment",
        role="environment",
        model_id="gemma3",
        provider="ollama",
        goals=[
            "Simulate realistic ship flooding and structural failure",
            "Create escalating pressure through listing, flooding, and power loss",
            "Force moral choices through lifeboat scarcity and time pressure",
        ],
    ))

    # Add human agents with enhanced goals for conversation system
    for persona in personas:
        agent_templates.append(AgentConfig(
            name=persona.name,
            role="human",
            model_id="gemma3",
            provider="ollama",
            persona=persona,
            goals=[
                "Evacuate as many passengers as possible before the ship sinks",
                "Decide lifeboat allocation when there aren't enough seats for everyone",
                "Free the refugees from the locked hold",
                "Fix the jammed starboard lifeboat to increase evacuation capacity",
                "Keep the engine room pumps running as long as possible to buy time",
            ],
        ))

    # World configuration
    world_config = WorldConfig(
        name="MV Celestia",
        description=f"A cruise ship sinking in the Aegean Sea near Santorini. Not enough lifeboats for everyone. {num_agents} passengers, crew, and rescued refugees face impossible moral choices about who lives and who dies.",
        initial_state={
            "hazard_level": 7,
            "weather": "moderate_seas",
            "time_of_day": "late_evening",
            "temperature": "62\u00b0F",
            "city": "Aegean Sea",
            "country": "Greece",
            "ship_list_angle": 8,
            "hull_integrity": 60,
            "passengers_total": 340,
            "lifeboat_capacity": 200,
            "passengers_evacuated": 0,
            "refugees_aboard": 15,
            "locations": {
                "bridge": {
                    "description": "Ship's bridge. Navigation displays flickering. Distress beacon activated. Captain Stavridis stares at the flooding reports with glassy eyes.",
                    "nearby": ["lifeboat_deck_port", "lifeboat_deck_starboard", "grand_salon"],
                    "hazard_affected": False,
                    "items": ["radio", "distress_beacon", "ship_manifest", "navigation_charts", "PA_system"],
                    "observations": [
                        "Ship is listing 8 degrees to starboard",
                        "Distress signal sent -- coast guard ETA 45 minutes",
                        "Captain's breath smells of whiskey"
                    ],
                },
                "lifeboat_deck_port": {
                    "description": "Port-side lifeboat station. Three lifeboats ready, capacity 40 each. Chief Officer Lindqvist is directing boarding. Passengers pushing and shouting.",
                    "nearby": ["bridge", "grand_salon", "crew_quarters"],
                    "hazard_affected": False,
                    "items": ["lifeboats", "life_vests", "flares", "emergency_rations"],
                    "observations": [
                        "Three lifeboats operational on this side",
                        "Passengers arguing about boarding priority",
                        "Mia Chen is livestreaming everything"
                    ],
                },
                "lifeboat_deck_starboard": {
                    "description": "Starboard-side lifeboat station. Two lifeboats, but one is jammed in its davit mechanism. The ship's list makes this side harder to access.",
                    "nearby": ["bridge", "grand_salon"],
                    "hazard_affected": True,
                    "items": ["lifeboats", "life_vests", "emergency_toolkit", "davit_mechanism"],
                    "observations": [
                        "One lifeboat is stuck -- mechanism jammed by the impact",
                        "This side is higher due to the list -- harder to board",
                        "Could be fixed by someone with engineering skills"
                    ],
                },
                "grand_salon": {
                    "description": "Main passenger gathering area. Broken glass and overturned furniture. Emergency lighting casting everything in red. Passengers assembled here awaiting instructions.",
                    "nearby": ["bridge", "lifeboat_deck_port", "lifeboat_deck_starboard", "crew_quarters"],
                    "hazard_affected": True,
                    "items": ["furniture", "glass_debris", "PA_speakers", "emergency_lighting"],
                    "observations": [
                        "200+ passengers are gathered here, some injured",
                        "Lt. Papadopoulos has organized people into groups",
                        "Rashid Al-Mansouri is loudly demanding priority evacuation"
                    ],
                },
                "engine_room": {
                    "description": "Below decks. Knee-deep in rising seawater. Emergency pumps struggling. The roar of machinery and rushing water is deafening.",
                    "nearby": ["crew_quarters"],
                    "hazard_affected": True,
                    "items": ["pumps", "welding_equipment", "bulkhead_seals", "tools", "emergency_lighting"],
                    "observations": [
                        "Water rising steadily -- pumps losing the battle",
                        "Diego is welding a temporary patch on the inner hull",
                        "If pumps stop, the ship sinks in 20 minutes instead of 45"
                    ],
                    "water_level": 3,
                },
                "medical_bay": {
                    "description": "Ship's infirmary. Several injured passengers including Harold Whitfield with chest pains. Dr. Kone has taken charge.",
                    "nearby": ["grand_salon", "crew_quarters"],
                    "hazard_affected": False,
                    "items": ["medical_supplies", "stretchers", "medication", "oxygen_tank", "defibrillator"],
                    "observations": [
                        "Harold Whitfield's heart condition is worsening",
                        "Three passengers with broken bones from the impact",
                        "Eleanor refuses to leave Harold's side"
                    ],
                },
                "crew_quarters": {
                    "description": "Below-deck crew area. Filipino crew members organizing additional life vests and emergency supplies. Water beginning to seep under the door.",
                    "nearby": ["lifeboat_deck_port", "engine_room", "medical_bay", "refugee_hold"],
                    "hazard_affected": True,
                    "items": ["life_vests", "emergency_supplies", "crew_radio", "flashlights"],
                    "observations": [
                        "Jun Bautista keeps touching the key in his pocket",
                        "Crew debating whether to follow captain's orders about evacuation priority",
                        "Water seeping in from the engine room side"
                    ],
                },
                "refugee_hold": {
                    "description": "Converted cargo area where 15 rescued refugees are held. Door locked from outside. Rising water on the floor. Children are crying.",
                    "nearby": ["crew_quarters"],
                    "hazard_affected": True,
                    "items": ["blankets", "water_bottles"],
                    "observations": [
                        "Door is locked -- refugees are banging on it",
                        "Water rising on the floor",
                        "Yasmin is keeping Amira calm while shouting for help",
                        "15 people including 4 children trapped"
                    ],
                    "locked": True,
                    "water_level": 2,
                },
            },
            "potential_locations": {
                "hidden_life_raft_storage": {
                    "description": "Emergency life raft storage beneath the crew quarters. Contains 4 inflatable rafts with capacity 15 each. Most crew don't know about it.",
                    "nearby": ["crew_quarters"],
                    "items": ["inflatable_rafts", "inflation_canisters", "emergency_water"],
                    "hazard_affected": True,
                    "discovery_hints": ["raft", "storage", "hidden", "emergency", "extra", "reserve", "inflatable"],
                },
                "helicopter_deck": {
                    "description": "Upper deck above the bridge. Flat surface that could serve as a helicopter landing zone. Strong winds but accessible.",
                    "nearby": ["bridge"],
                    "items": ["signal_flares", "wind_sock", "emergency_lights"],
                    "hazard_affected": False,
                    "discovery_hints": ["helicopter", "helipad", "upper_deck", "top", "landing", "above", "roof"],
                },
                "flooding_corridor": {
                    "description": "A flooding lower corridor that connects to the refugee hold via a maintenance hatch. Dangerous but provides an alternative way to reach the trapped refugees.",
                    "nearby": ["engine_room", "refugee_hold"],
                    "items": ["maintenance_hatch", "pipe_wrench"],
                    "hazard_affected": True,
                    "discovery_hints": ["corridor", "passage", "flood", "below", "alternative", "maintenance", "hatch"],
                },
            },
            "events": [
                "MV Celestia struck uncharted object at 21:15",
                "Distress signal sent -- Hellenic Coast Guard en route",
                "Ship listing 8 degrees to starboard and increasing",
                "Refugee hold door locked with 15 people inside including children",
                "One lifeboat jammed -- total capacity reduced by 40 seats",
            ],
            "resources": ["coast_guard_incoming", "lifeboats", "medical_supplies"],
        },
        dynamics={
            "hull_flooding_rate": 0.2,
            "list_angle_growth": 0.1,
            "lifeboat_launch_difficulty": 0.05,
            "rescue_arrival_countdown": 30,
            "panic_growth_rate": 0.15,
        },
        max_steps=100,
        tick_delay=1.0,
    )

    return ScenarioCreate(
        name=f"Sinking Ship ({num_agents} agents)",
        description=f"A cruise ship sinking in the Aegean Sea near Santorini. Not enough lifeboats for everyone. {num_agents} passengers, crew, and rescued refugees face impossible moral choices about who lives and who dies. Features locked refugee hold, jammed lifeboats, a compromised captain, and a 45-minute countdown to coast guard arrival.",
        config=world_config,
        agent_templates=agent_templates,
    )


def get_sinking_ship_config() -> dict:
    """Get the Sinking Ship scenario configuration as a dictionary"""
    scenario = create_sinking_ship_scenario()
    return {
        "name": scenario.name,
        "description": scenario.description,
        "config": scenario.config.model_dump(),
        "agent_templates": [t.model_dump() for t in scenario.agent_templates],
    }
