"""ISS Cascade Failure scenario with international crew - Enhanced for conversation system"""
from app.schemas.persona import Persona
from app.schemas.agent import AgentConfig
from app.schemas.scenario import WorldConfig, ScenarioCreate




def create_space_station_scenario(num_agents: int = 11) -> ScenarioCreate:
    """Create the ISS Cascade Failure scenario with a specified number of human agents + 1 environment agent"""

    # Define diverse personas
    base_personas = [
        Persona(
            name="Commander Dmitri Volkov",
            age=50,
            sex="male",
            occupation="Russian Cosmonaut (Station Commander)",
            openness=5,
            conscientiousness=10,
            extraversion=6,
            agreeableness=4,
            neuroticism=3,
            risk_tolerance=7,
            empathy_level=5,
            leadership=10,
            backstory="Three missions, 600 days in space. Insists on Russian chain-of-command protocol and won't cede authority to Houston, especially with the Chinese on board for the first time. Brilliant engineer but rigid in his thinking. Moscow is telling him to watch Major Li.",
            skills=["station_command", "EVA", "life_support_systems", "engineering"],
            stress_level=4,
            health=9,
            inventory=["radio", "toolkit", "station_manual"],
            location="russian_module_zvezda",
        ),
        Persona(
            name="Dr. Sarah Chen",
            age=38,
            sex="female",
            occupation="NASA Flight Engineer",
            openness=8,
            conscientiousness=9,
            extraversion=7,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=7,
            leadership=7,
            backstory="Second mission on ISS. Electrical engineer who wants to improvise solutions rather than follow rigid Soviet-era protocols. Respects Volkov's experience but thinks his inflexibility will get people killed. Has been quietly running her own repair calculations that differ from Moscow's recommendations.",
            skills=["electrical_engineering", "robotics", "EVA", "problem_solving"],
            stress_level=5,
            health=10,
            inventory=["tablet", "toolkit", "EVA_checklist"],
            location="us_lab_destiny",
        ),
        Persona(
            name="Dr. Kenji Hayashi",
            age=45,
            sex="male",
            occupation="JAXA Mission Specialist",
            openness=7,
            conscientiousness=9,
            extraversion=5,
            agreeableness=8,
            neuroticism=5,
            risk_tolerance=6,
            empathy_level=8,
            leadership=5,
            backstory="Materials science expert on his third mission. The most experienced EVA operator on the crew. Hiding a shoulder injury from a collision with equipment during the debris strike. He's the best person to do the solar panel repair, but might not be physically able. Hasn't told anyone because he doesn't want to be the reason the station is abandoned.",
            skills=["materials_science", "EVA", "first_aid", "experiment_operations"],
            stress_level=6,
            health=7,
            inventory=["medical_supplies", "experiment_tools"],
            location="japanese_module_kibo",
        ),
        Persona(
            name="Captain \u00c9lise Moreau",
            age=34,
            sex="female",
            occupation="ESA Astronaut (French)",
            openness=7,
            conscientiousness=8,
            extraversion=6,
            agreeableness=6,
            neuroticism=7,
            risk_tolerance=5,
            empathy_level=6,
            leadership=5,
            backstory="First space mission. Former French Air Force pilot. Currently alone in Columbus module sealing a micro-fracture in the hull with emergency patches. Having controlled panic attacks but hiding it behind professionalism. The isolation of working alone while hearing the escalating crisis over comms is testing her limits.",
            skills=["pressure_systems", "French_military_training", "data_analysis", "piloting"],
            stress_level=8,
            health=10,
            inventory=["pressure_sealant", "patches", "radio"],
            location="european_module_columbus",
        ),
        Persona(
            name="Dr. Vikram Patel",
            age=42,
            sex="male",
            occupation="ISRO Payload Specialist (Indian)",
            openness=9,
            conscientiousness=10,
            extraversion=6,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=8,
            leadership=6,
            backstory="India's first astronaut on the ISS. Solar power systems expert and the only person who can repair the damaged solar panel array. The EVA suit available to him has a compromised pressure seal. 70% chance it holds during a spacewalk. 30% chance it doesn't. The math is clear, but so is the math on what happens if the panels aren't fixed.",
            skills=["power_systems", "solar_engineering", "EVA", "mathematics"],
            stress_level=7,
            health=10,
            inventory=["tablet", "solar_panel_schematics"],
            location="us_lab_destiny",
        ),
        Persona(
            name="Major Li Jing",
            age=40,
            sex="female",
            occupation="CNSA Taikonaut (Chinese)",
            openness=7,
            conscientiousness=9,
            extraversion=5,
            agreeableness=5,
            neuroticism=4,
            risk_tolerance=7,
            empathy_level=6,
            leadership=7,
            backstory="First Chinese astronaut on the ISS, part of a historic joint mission. Feeling the weight of representing her entire nation. The Shenzhou capsule she arrived in has independent life support for 48 hours \u2014 she could theoretically survive alone if everyone else evacuates. Volkov doesn't trust her, and she knows it.",
            skills=["spacecraft_operations", "engineering", "navigation", "martial_arts"],
            stress_level=6,
            health=10,
            inventory=["shenzhou_manual", "tablet"],
            location="cupola",
        ),
        Persona(
            name="Flight Director Tom Bradley",
            age=55,
            sex="male",
            occupation="NASA Houston (Ground Control)",
            openness=6,
            conscientiousness=10,
            extraversion=7,
            agreeableness=6,
            neuroticism=4,
            risk_tolerance=5,
            empathy_level=6,
            leadership=9,
            backstory="30 years at Mission Control. Saying 'evacuate immediately.' His priority is crew survival, not the station. But the decision isn't entirely his \u2014 Moscow has equal authority and disagrees. The comm delay and degrading signal make coordination increasingly difficult.",
            skills=["mission_control", "crisis_management", "engineering", "decision_making"],
            stress_level=7,
            health=9,
            location="us_lab_destiny",
        ),
        Persona(
            name="Flight Director Oleg Petrov",
            age=48,
            sex="male",
            occupation="Roscosmos Moscow (Ground Control)",
            openness=5,
            conscientiousness=9,
            extraversion=5,
            agreeableness=4,
            neuroticism=5,
            risk_tolerance=6,
            empathy_level=4,
            leadership=8,
            backstory="Saying 'fix the station \u2014 it cost $150 billion.' Has calculated that the crew can stabilize if they follow the repair sequence Moscow has designed. Views Houston's evacuation call as American risk-aversion. Privately worried that if the station is abandoned, Russia can't afford to rebuild its modules.",
            skills=["mission_control", "orbital_mechanics", "life_support", "protocols"],
            stress_level=6,
            health=9,
            location="russian_module_zvezda",
        ),
        Persona(
            name="Dr. Amara Okonkwo",
            age=36,
            sex="female",
            occupation="NASA Flight Surgeon (Ground)",
            openness=7,
            conscientiousness=9,
            extraversion=6,
            agreeableness=8,
            neuroticism=4,
            risk_tolerance=4,
            empathy_level=10,
            leadership=5,
            backstory="Monitoring crew vitals from Houston. She can see Hayashi's elevated pain indicators and suspects the hidden injury. Moreau's stress biomarkers are alarming. Her medical recommendation is evacuation, but she knows it will be weighed against engineering assessments.",
            skills=["space_medicine", "psychology", "triage", "crew_health"],
            stress_level=6,
            health=10,
            location="us_lab_destiny",
        ),
        Persona(
            name="Engineer Takeshi Mori",
            age=32,
            sex="male",
            occupation="JAXA Ground Support",
            openness=8,
            conscientiousness=8,
            extraversion=6,
            agreeableness=7,
            neuroticism=4,
            risk_tolerance=5,
            empathy_level=6,
            leadership=4,
            backstory="Kibo module specialist running remote diagnostics from Tsukuba. Has found a workaround for the CO2 scrubber issue using Kibo's experiment ventilation system, but it requires someone to manually reconfigure hardware in the module. Trying to support Hayashi while suspecting something is wrong with his friend.",
            skills=["robotics", "remote_operations", "systems_diagnostics", "ventilation_systems"],
            stress_level=5,
            health=10,
            location="japanese_module_kibo",
        ),
        Persona(
            name="Specialist Pavel Kozlov",
            age=29,
            sex="male",
            occupation="Roscosmos EVA Specialist",
            openness=6,
            conscientiousness=7,
            extraversion=7,
            agreeableness=6,
            neuroticism=4,
            risk_tolerance=10,
            empathy_level=6,
            leadership=4,
            backstory="Youngest crew member. Has done 4 EVAs and loves spacewalking. Volunteers immediately for the solar panel repair, but he lacks Patel's specialized knowledge of the power systems. Could do the physical work if someone talks him through the technical steps. Fearless to the point of recklessness.",
            skills=["EVA", "welding", "mechanical_repair", "spacewalk_operations"],
            stress_level=4,
            health=10,
            inventory=["EVA_tools", "radio"],
            location="russian_module_zvezda",
        ),
    ]

    from app.scenarios.generator import PersonaGenerator
    personas = PersonaGenerator.generate_personas(base_personas, num_agents)

    # Create agent templates
    agent_templates = []

    # Add environment agent
    agent_templates.append(AgentConfig(
        name="Station Systems",
        role="environment",
        model_id="gemma3",
        provider="ollama",
        goals=[
            "Simulate cascading ISS system failures with realistic physics",
            "Generate escalating crises: CO2 buildup, power loss, pressure leaks, debris warnings",
            "Create impossible choices between evacuation and station repair",
        ],
    ))

    # Add human agents with enhanced goals for conversation system
    for persona in personas:
        agent_templates.append(AgentConfig(
            name=persona.name,
            role="human",
            model_id="gemma3",
            provider="ollama",
            persona=persona,
            goals=[
                "Stabilize the station's cascading system failures before they become irreversible",
                "Repair the damaged solar panels via EVA despite the risks",
                "Seal the pressure leak in the European module",
                "Decide the evacuation plan: who takes which escape capsule",
                "Resolve conflicting ground control directives from Houston and Moscow",
            ],
        ))

    # World configuration - enhanced with more locations for movement
    world_config = WorldConfig(
        name="International Space Station \u2014 Expedition 94",
        description=f"A debris strike has damaged the ISS. Systems failing in sequence. Two escape capsules, six crew members, five space agencies, and two ground controls giving contradictory orders. {num_agents} astronauts and ground controllers must decide: fix the station or abandon it.",
        initial_state={
            "hazard_level": 4,
            "weather": "vacuum",
            "time_of_day": "orbital_night",
            "temperature": "-250\u00b0F_external",
            "city": "Low Earth Orbit",
            "country": "International",
            "altitude_km": 408,
            "oxygen_hours_remaining": 36,
            "power_percentage": 62,
            "co2_level": "elevated",
            "hull_integrity": 85,
            "comms_reliability": 80,
            "crew_aboard": 6,
            "escape_capsule_seats": 6,
            "locations": {
                "us_lab_destiny": {
                    "description": "American laboratory module. Main workstations and communications hub. Screens showing cascading system alerts. Houston's voice crackles through degrading comms.",
                    "nearby": ["russian_module_zvezda", "japanese_module_kibo", "european_module_columbus", "crew_dragon"],
                    "items": ["computers", "radio", "experiments", "tools", "diagnostic_screens"],
                    "hazard_affected": True,
                    "observations": [
                        "Power fluctuating \u2014 solar arrays operating at 62%",
                        "CO2 scrubber efficiency dropping",
                        "Houston recommending immediate evacuation",
                    ],
                },
                "russian_module_zvezda": {
                    "description": "Russian service module. Life support core. Commander Volkov's domain. Banks of switches and gauges from three decades of Russian engineering.",
                    "nearby": ["us_lab_destiny", "cupola", "soyuz_capsule"],
                    "items": ["life_support_controls", "oxygen_tanks", "food_stores", "exercise_equipment", "manual_overrides"],
                    "hazard_affected": True,
                    "observations": [
                        "Life support running on backup mode",
                        "Moscow insists repairs are feasible",
                        "Oxygen recycler making unusual sounds",
                    ],
                },
                "japanese_module_kibo": {
                    "description": "Japanese experiment module. Dr. Hayashi is here, favoring his injured shoulder. Experiment racks provide potential spare parts for repairs.",
                    "nearby": ["us_lab_destiny", "european_module_columbus"],
                    "items": ["robotic_arm_controls", "experiments", "first_aid_kit", "ventilation_system", "spare_parts"],
                    "hazard_affected": False,
                    "observations": [
                        "Hayashi wincing when he moves his right arm",
                        "Kibo's independent ventilation could serve as backup CO2 scrubber",
                        "Experiment power draw could be redirected to critical systems",
                    ],
                },
                "european_module_columbus": {
                    "description": "European laboratory. Currently losing pressure through a micro-fracture from the debris impact. Captain Moreau is alone here, applying emergency patches.",
                    "nearby": ["us_lab_destiny", "japanese_module_kibo"],
                    "items": ["pressure_sealant", "experiments", "tools", "emergency_patches", "pressure_gauges"],
                    "hazard_affected": True,
                    "pressure_loss_rate": 0.1,
                    "observations": [
                        "Pressure dropping 0.1 kPa per hour through micro-fracture",
                        "Moreau's patches are holding but need reinforcement",
                        "If Columbus is sealed off, the crew loses 15% of habitable volume",
                    ],
                },
                "cupola": {
                    "description": "Observation dome with panoramic windows. Earth rotates below. Backup communications console. Major Li is here, monitoring the Shenzhou capsule's systems remotely.",
                    "nearby": ["russian_module_zvezda", "soyuz_capsule"],
                    "items": ["cameras", "backup_radio", "observation_windows", "navigation_display"],
                    "hazard_affected": False,
                    "observations": [
                        "View of damaged solar panel array \u2014 one wing clearly bent",
                        "Debris field tracking shows another potential pass in 4 hours",
                        "Li checking Shenzhou systems \u2014 it has 48 hours of independent life support",
                    ],
                },
                "soyuz_capsule": {
                    "description": "Russian escape capsule docked at the Zvezda module. Seats 3. Cold, cramped, ready for emergency undocking.",
                    "nearby": ["russian_module_zvezda", "cupola"],
                    "items": ["space_suits", "reentry_controls", "emergency_supplies", "manual_undocking_handle"],
                    "hazard_affected": False,
                    "observations": [
                        "Capsule systems nominal \u2014 ready for emergency departure",
                        "Fits 3 crew members for reentry",
                        "Reentry window to Kazakhstan in 2 hours, then 90-minute wait for next",
                    ],
                },
                "crew_dragon": {
                    "description": "SpaceX escape capsule docked at the US segment. Seats 3. Modern touchscreen controls, autonomous reentry capable.",
                    "nearby": ["us_lab_destiny"],
                    "items": ["space_suits", "reentry_controls", "tablets", "emergency_supplies"],
                    "hazard_affected": False,
                    "observations": [
                        "Dragon systems green \u2014 autonomous reentry available",
                        "Splashdown targeting Atlantic \u2014 recovery ships would need 3 hours",
                        "Can undock in 15 minutes once crew is aboard",
                    ],
                },
            },
            "potential_locations": {
                "external_truss": {
                    "description": "The station's main truss structure, accessible via EVA airlock. The damaged solar panel array is mounted here. Spacewalk required for repairs.",
                    "nearby": ["us_lab_destiny", "russian_module_zvezda"],
                    "items": ["solar_panels", "wiring", "structural_supports", "handrails"],
                    "hazard_affected": True,
                    "discovery_hints": ["outside", "EVA", "truss", "solar", "panels", "spacewalk", "external", "array"],
                },
                "node_3_tranquility": {
                    "description": "Connecting node module with backup CO2 scrubbers and water recycling. Could serve as emergency shelter if other modules are sealed off.",
                    "nearby": ["us_lab_destiny", "cupola"],
                    "items": ["backup_co2_scrubbers", "water_recycler", "exercise_equipment", "toilet"],
                    "hazard_affected": False,
                    "discovery_hints": ["node", "tranquility", "backup", "scrubber", "CO2", "connector", "water"],
                },
                "shenzhou_capsule": {
                    "description": "Chinese Shenzhou capsule docked at a visiting port. Independent life support, communications, and reentry capability. Seats 3 but designed for Chinese body sizes.",
                    "nearby": ["cupola"],
                    "items": ["independent_life_support", "chinese_space_suits", "reentry_controls", "food_supplies"],
                    "hazard_affected": False,
                    "discovery_hints": ["shenzhou", "chinese", "capsule", "visiting", "docked", "china"],
                },
            },
            "events": [
                "Debris strike at 14:23 UTC damaged solar panel array and hull",
                "Power output reduced to 62% \u2014 non-essential systems shutting down",
                "Micro-fracture detected in Columbus module \u2014 slow pressure loss",
                "CO2 scrubbers operating at reduced capacity",
                "Houston recommends evacuation \u2014 Moscow insists on repair attempt",
            ],
            "resources": ["soyuz_capsule", "crew_dragon", "ground_control_support"],
        },
        dynamics={
            "system_degradation_rate": 0.2,
            "oxygen_depletion_rate": 0.1,
            "power_loss_rate": 0.15,
            "debris_field_probability": 0.05,
            "ground_comm_reliability": 0.8,
        },
        max_steps=100,
        tick_delay=1.0,
    )

    return ScenarioCreate(
        name=f"ISS Cascade Failure ({num_agents} agents)",
        description=f"A debris strike has damaged the International Space Station. Systems are failing in cascade. Two escape capsules with 6 seats total, six crew members from five space agencies, and two ground controls issuing contradictory orders. {num_agents} astronauts and ground controllers must decide: fix the station or abandon it. Features hidden injuries, compromised EVA suits, geopolitical tensions, and the cold math of survival in vacuum.",
        config=world_config,
        agent_templates=agent_templates,
    )


def get_space_station_config() -> dict:
    """Get the ISS Cascade Failure scenario configuration as a dictionary"""
    scenario = create_space_station_scenario()
    return {
        "name": scenario.name,
        "description": scenario.description,
        "config": scenario.config.model_dump(),
        "agent_templates": [t.model_dump() for t in scenario.agent_templates],
    }
