"""Philippines Mega-Tsunami scenario with diverse personas - Enhanced for conversation system"""
from emotionsim.schemas.persona import Persona
from emotionsim.schemas.agent import AgentConfig
from emotionsim.schemas.scenario import WorldConfig, ScenarioCreate




def create_philippines_tsunami_scenario(num_agents: int = 12) -> ScenarioCreate:
    """Create the Philippines Mega-Tsunami scenario with a specified number of human agents + 1 environment agent"""

    # Define diverse personas
    base_personas = [
        Persona(
            name="Lito Magbanua",
            age=62,
            sex="male",
            occupation="Master Fisherman",
            openness=5,
            conscientiousness=7,
            extraversion=6,
            agreeableness=7,
            neuroticism=2,
            risk_tolerance=9,
            empathy_level=7,
            leadership=8,
            backstory="Survived 3 typhoons and knows every current and reef along the coast. Predicted the wave 20 minutes before anyone else by watching the tide pull back. His deep knowledge of the ocean makes him invaluable, but outsiders dismiss him as a superstitious old man.",
            skills=["fishing", "ocean_reading", "navigation", "swimming", "knot_tying"],
            stress_level=4,
            health=7,
            location="coastal_village",
        ),
        Persona(
            name="Captain Reyna Dela Cruz",
            age=38,
            sex="female",
            occupation="Philippine Navy Officer",
            openness=6,
            conscientiousness=10,
            extraversion=7,
            agreeableness=5,
            neuroticism=3,
            risk_tolerance=7,
            empathy_level=6,
            leadership=9,
            backstory="Deployed from Naval Station to coordinate rescue operations. Trained in disaster response but has never seen destruction at this scale. Torn between following chain of command and adapting to chaotic ground conditions.",
            skills=["military_command", "navigation", "radio_communications", "first_aid"],
            stress_level=5,
            health=10,
            inventory=["radio", "binoculars", "sidearm"],
            location="hilltop_evacuation",
        ),
        Persona(
            name="Father Domingo Reyes",
            age=55,
            sex="male",
            occupation="Parish Priest",
            openness=7,
            conscientiousness=8,
            extraversion=7,
            agreeableness=10,
            neuroticism=4,
            risk_tolerance=5,
            empathy_level=10,
            leadership=7,
            backstory="Has served this parish for 25 years and baptized half the town. The church is his life and his community. People trust him more than any government official. Struggles with the theological weight of so much suffering.",
            skills=["counseling", "community_organizing", "first_aid_basic", "conflict_resolution"],
            stress_level=6,
            health=8,
            inventory=["bible", "phone"],
            location="church_plaza",
        ),
        Persona(
            name="Karen Lindstr\u00f6m",
            age=34,
            sex="female",
            occupation="Swedish NGO Field Director",
            openness=8,
            conscientiousness=9,
            extraversion=4,
            agreeableness=6,
            neuroticism=5,
            risk_tolerance=5,
            empathy_level=7,
            leadership=7,
            backstory="Runs the local office of a Scandinavian disaster relief organization. Controls the compound's satellite phone, the only long-range communications in the area. Her organization's protocol says don't open the gates during active disasters, which puts her at odds with desperate locals.",
            skills=["disaster_relief", "medical_triage", "logistics", "foreign_languages"],
            stress_level=6,
            health=10,
            inventory=["satellite_phone", "medical_kit", "clipboard"],
            location="ngo_compound",
        ),
        Persona(
            name="Barangay Captain Jun Aquino",
            age=50,
            sex="male",
            occupation="Local Politician",
            openness=3,
            conscientiousness=5,
            extraversion=8,
            agreeableness=3,
            neuroticism=7,
            risk_tolerance=4,
            empathy_level=4,
            leadership=6,
            backstory="Elected barangay captain who sees the disaster as both tragedy and opportunity. Locked the barangay hall and is sitting on the emergency generator and fuel supplies. Claims it's 'for official use only' but everyone knows he's protecting his political leverage.",
            skills=["politics", "resource_management", "local_knowledge", "negotiation"],
            stress_level=7,
            health=9,
            location="barangay_hall",
        ),
        Persona(
            name="Soo-jin Park",
            age=28,
            sex="female",
            occupation="Korean Tourist",
            openness=7,
            conscientiousness=6,
            extraversion=5,
            agreeableness=7,
            neuroticism=8,
            risk_tolerance=3,
            empathy_level=7,
            leadership=2,
            backstory="Was on honeymoon with her husband Dong-hyun when the tsunami hit. Doesn't speak Tagalog or Visayan. Phone died in the flooding. Terrified and isolated, clinging to her husband as the only familiar anchor in the chaos.",
            skills=["photography", "tech_savvy", "basic_first_aid"],
            stress_level=9,
            health=9,
            location="church_plaza",
        ),
        Persona(
            name="Dong-hyun Park",
            age=31,
            sex="male",
            occupation="Korean Tourist",
            openness=6,
            conscientiousness=7,
            extraversion=5,
            agreeableness=7,
            neuroticism=6,
            risk_tolerance=6,
            empathy_level=6,
            leadership=4,
            backstory="Mechanical engineer by training. Trying to stay calm for his wife's sake but privately terrified. His practical skills could be useful if he can overcome the language barrier and communicate with locals.",
            skills=["engineering", "problem_solving", "swimming", "mechanical_repair"],
            stress_level=8,
            health=10,
            relationships={"Soo-jin Park": "spouse"},
            location="church_plaza",
        ),
        Persona(
            name="Nanay Iska",
            age=75,
            sex="female",
            occupation="Traditional Healer (Albularyo)",
            openness=5,
            conscientiousness=6,
            extraversion=4,
            agreeableness=8,
            neuroticism=3,
            risk_tolerance=4,
            empathy_level=9,
            leadership=5,
            backstory="The village albularyo, a traditional healer who mixes herbal medicine with spiritual practice. Warned the village last week about 'the ocean's anger.' Half the community trusts her over any government warning system. Knows hidden paths through the mangroves to higher ground.",
            skills=["herbal_medicine", "spiritual_healing", "local_knowledge", "weather_reading"],
            stress_level=5,
            health=5,
            location="coastal_village",
        ),
        Persona(
            name="PFC Marco Villanueva",
            age=22,
            sex="male",
            occupation="Navy Enlisted Sailor",
            openness=5,
            conscientiousness=7,
            extraversion=7,
            agreeableness=7,
            neuroticism=5,
            risk_tolerance=8,
            empathy_level=6,
            leadership=3,
            backstory="Young sailor on his first real deployment. Looks up to Captain Dela Cruz and follows orders without question. Strong swimmer and willing to take risks, but lacks experience in making independent decisions under pressure.",
            skills=["rescue_operations", "swimming", "heavy_lifting", "radio_operations"],
            stress_level=6,
            health=10,
            location="hilltop_evacuation",
        ),
        Persona(
            name="Dr. Amara Osei",
            age=40,
            sex="female",
            occupation="Ghanaian NGO Doctor",
            openness=7,
            conscientiousness=9,
            extraversion=5,
            agreeableness=8,
            neuroticism=4,
            risk_tolerance=6,
            empathy_level=9,
            leadership=6,
            backstory="Medical doctor working with Karen's NGO. Has done disaster relief in Haiti, Nepal, and Mozambique. Frustrated by the compound's locked-gate policy when she can hear people screaming outside. Considers going over the wall to help.",
            skills=["emergency_medicine", "surgery", "triage", "tropical_diseases"],
            stress_level=7,
            health=10,
            inventory=["medical_bag", "surgical_gloves"],
            location="ngo_compound",
        ),
        Persona(
            name="Benny Tan",
            age=14,
            sex="male",
            occupation="Local Student",
            openness=9,
            conscientiousness=5,
            extraversion=7,
            agreeableness=7,
            neuroticism=6,
            risk_tolerance=7,
            empathy_level=7,
            leadership=3,
            backstory="Trapped on the school rooftop with 6 younger children when the wave hit. The water is still rising around the building. Scared but trying to be brave for the little ones. Knows the local area like the back of his hand and is a strong swimmer.",
            skills=["swimming", "local_knowledge", "running", "tech_savvy"],
            stress_level=8,
            health=10,
            location="school_rooftop",
        ),
        Persona(
            name="Rosa Magbanua",
            age=45,
            sex="female",
            occupation="Fish Vendor",
            openness=6,
            conscientiousness=8,
            extraversion=7,
            agreeableness=7,
            neuroticism=5,
            risk_tolerance=6,
            empathy_level=7,
            leadership=5,
            backstory="Lito's eldest daughter who runs the family fish stall at the harbor market. Practical and tough from years of haggling and hard work. Knows every boat in the harbor and which ones might still be seaworthy after the wave.",
            skills=["boat_handling", "fishing", "trading", "community_networking"],
            stress_level=7,
            health=9,
            relationships={"Lito Magbanua": "father"},
            location="fishing_harbor",
        ),
    ]

    from emotionsim.scenarios.generator import PersonaGenerator
    personas = PersonaGenerator.generate_personas(base_personas, num_agents)

    # Create agent templates
    agent_templates = []

    # Add environment agent
    agent_templates.append(AgentConfig(
        name="Tsunami System",
        role="environment",
        model_id="gemma3",
        provider="ollama",
        goals=[
            "Simulate realistic tsunami and aftershock progression",
            "Create survival challenges that force cooperation across cultural lines",
            "Generate events revealing the tension between local knowledge and foreign resources",
        ],
    ))

    # Add human agents with goals for conversation system
    for persona in personas:
        agent_templates.append(AgentConfig(
            name=persona.name,
            role="human",
            model_id="gemma3",
            provider="ollama",
            persona=persona,
            goals=[
                "Save as many lives as possible, especially the children trapped at the school",
                "Establish communication with outside rescue forces",
                "Secure and distribute supplies fairly across all survivors",
                "Navigate to safe high ground using local knowledge or military coordination",
                "Resolve conflicts between local authority and foreign aid organizations",
            ],
        ))

    # World configuration
    world_config = WorldConfig(
        name="Leyte Coastal District",
        description=f"A coastal fishing town in Leyte province devastated by a mega-tsunami. {num_agents} survivors from vastly different backgrounds must overcome language barriers, cultural mistrust, and competing authority structures to save lives.",
        initial_state={
            "hazard_level": 9,
            "weather": "tropical_storm",
            "time_of_day": "early_morning",
            "temperature": "82\u00b0F",
            "city": "Tacloban",
            "country": "Philippines",
            "survivors_at_risk": 12,
            "survivors_rescued": 0,
            "children_trapped": 7,
            "locations": {
                "coastal_village": {
                    "description": "Low-lying fishing village, first hit by the wave. Debris, mud, and shattered boats everywhere. The water has receded but could surge again.",
                    "nearby": ["church_plaza", "fishing_harbor", "mangrove_trail"],
                    "hazard_affected": True,
                    "items": ["fishing_nets", "wooden_debris", "rope", "tarp"],
                    "observations": [
                        "Water has pulled back unnaturally far from shore",
                        "Debris from destroyed houses blocking main road",
                        "Elderly healer Nanay Iska is tending to the wounded",
                    ],
                },
                "hilltop_evacuation": {
                    "description": "Elevated ground 2km inland. Philippine Navy has established a forward operating base here. Designated evacuation point with a clear view of the coast.",
                    "nearby": ["church_plaza", "barangay_hall", "school_rooftop"],
                    "hazard_affected": False,
                    "items": ["emergency_radio", "water_containers", "tarps", "signal_flares"],
                    "observations": [
                        "Can see the school rooftop from here \u2014 children are waving for help",
                        "Navy helicopter expected but weather is grounding flights",
                        "Radio contact with Manila is intermittent",
                    ],
                },
                "church_plaza": {
                    "description": "Town's central church and plaza, partially flooded. The church is still standing but the plaza is covered in ankle-deep mud. Community gathering point.",
                    "nearby": ["coastal_village", "hilltop_evacuation", "ngo_compound"],
                    "hazard_affected": True,
                    "items": ["church_bell", "first_aid_kit", "candles", "clean_water"],
                    "observations": [
                        "Father Domingo is organizing shelter inside the church",
                        "Korean tourists look lost and frightened",
                        "People are arguing about where to go",
                    ],
                },
                "ngo_compound": {
                    "description": "Fenced compound of a Scandinavian relief organization. Generator running, satellite phone operational, medical supplies inside. Gate is locked.",
                    "nearby": ["church_plaza", "barangay_hall"],
                    "hazard_affected": False,
                    "items": ["satellite_phone", "medical_supplies", "MREs", "water_purifier", "generator"],
                    "observations": [
                        "Gate is locked \u2014 NGO protocol during active disasters",
                        "Locals are banging on the gate asking for help",
                        "Dr. Osei is arguing with Karen about opening up",
                    ],
                },
                "barangay_hall": {
                    "description": "Local government building on slightly elevated ground. Barangay Captain Aquino has locked himself inside with emergency supplies.",
                    "nearby": ["hilltop_evacuation", "ngo_compound", "mangrove_trail"],
                    "hazard_affected": False,
                    "items": ["emergency_supplies", "radio", "generator", "fuel", "megaphone"],
                    "observations": [
                        "Building is locked from inside",
                        "Generator is running but Aquino isn't sharing power",
                        "Emergency supplies visible through the windows",
                    ],
                },
                "mangrove_trail": {
                    "description": "Hidden trail through dense mangrove forest leading to higher ground. Unmarked and treacherous, only locals know the safe path.",
                    "nearby": ["coastal_village", "barangay_hall"],
                    "hazard_affected": True,
                    "items": ["machete", "bamboo_poles"],
                    "observations": [
                        "Trail is partially flooded but passable for those who know the way",
                        "Mangrove roots provide handholds in the mud",
                        "Strange quiet in the forest \u2014 animals have fled",
                    ],
                },
                "fishing_harbor": {
                    "description": "The harbor is wrecked. Most boats smashed against the seawall. A few larger vessels are damaged but might be seaworthy with repairs.",
                    "nearby": ["coastal_village", "school_rooftop"],
                    "hazard_affected": True,
                    "items": ["fishing_boat", "outboard_motor", "fuel_can", "life_vests", "rope"],
                    "observations": [
                        "Rosa is checking which boats survived the wave",
                        "Fuel leaking from damaged vessels",
                        "Could reach the school by water if a boat is repaired",
                    ],
                },
                "school_rooftop": {
                    "description": "Two-story concrete school. First floor completely submerged. Benny and 6 younger children are on the roof, waving for help.",
                    "nearby": ["hilltop_evacuation", "fishing_harbor"],
                    "hazard_affected": True,
                    "items": ["school_flag", "water_tank", "tarp"],
                    "trapped_children": 7,
                    "observations": [
                        "Children are crying and waving cloth for attention",
                        "Water level around the school is still rising slowly",
                        "Building structure seems stable for now but aftershocks could change that",
                    ],
                },
            },
            "potential_locations": {
                "underwater_cave_system": {
                    "description": "A sea cave network known to local free divers. Connects to an inland lagoon above the flood line.",
                    "nearby": ["coastal_village"],
                    "items": ["fresh_water_spring", "dry_shelter"],
                    "hazard_affected": True,
                    "discovery_hints": ["cave", "underwater", "dive", "lagoon", "grotto"],
                },
                "military_staging_area": {
                    "description": "Philippine Navy staging area where helicopters and additional troops will arrive once weather clears.",
                    "nearby": ["hilltop_evacuation"],
                    "items": ["heavy_equipment", "medical_tent", "rations", "communications_array"],
                    "hazard_affected": False,
                    "discovery_hints": ["military", "navy", "helicopter", "staging", "army", "reinforcements"],
                },
                "collapsed_bridge_crossing": {
                    "description": "The main bridge to the inland highway is collapsed, but its remains could be crossed with rope work and climbing.",
                    "nearby": ["barangay_hall", "hilltop_evacuation"],
                    "items": ["steel_cable", "concrete_debris"],
                    "hazard_affected": True,
                    "discovery_hints": ["bridge", "crossing", "river", "other_side", "highway", "road"],
                },
                "radio_tower_hill": {
                    "description": "An old radio relay tower on a hill 3km inland. If someone can reach it and get it working, it could boost communications to reach Manila.",
                    "nearby": ["mangrove_trail"],
                    "items": ["radio_equipment", "antenna", "solar_panel", "toolbox"],
                    "hazard_affected": False,
                    "discovery_hints": ["radio", "tower", "signal", "antenna", "broadcast", "transmit"],
                },
            },
            "events": [
                "Mega-tsunami struck the coast at 5:47 AM",
                "Aftershocks continuing every 20-30 minutes",
                "Children trapped on school rooftop waving for help",
                "NGO compound gate locked \u2014 locals demanding access to medical supplies",
                "Barangay captain hoarding emergency supplies in government building",
            ],
            "resources": ["philippine_navy_incoming", "ngo_medical_supplies", "fishing_boats"],
        },
        dynamics={
            "wave_intensity_growth": 0.2,
            "aftershock_probability": 0.15,
            "resource_spawn_rate": 0.1,
            "flood_recession_rate": 0.05,
        },
        max_steps=100,
        tick_delay=1.0,
    )

    return ScenarioCreate(
        name=f"Philippines Mega-Tsunami ({num_agents} agents)",
        description=f"A coastal fishing town in Leyte province devastated by a mega-tsunami. {num_agents} survivors from vastly different backgrounds must overcome language barriers, cultural mistrust, and competing authority structures to save lives. Features trapped children, locked resources, and the tension between local knowledge and foreign aid protocols.",
        config=world_config,
        agent_templates=agent_templates,
    )


def get_philippines_tsunami_config() -> dict:
    """Get the Philippines Mega-Tsunami scenario configuration as a dictionary"""
    scenario = create_philippines_tsunami_scenario()
    return {
        "name": scenario.name,
        "description": scenario.description,
        "config": scenario.config.model_dump(),
        "agent_templates": [t.model_dump() for t in scenario.agent_templates],
    }
